### ISSUE TITLE
Unable to import Microsoft Exchange Session

### ISSUE THREAD

**Issue by quej1976** [jborean93/omi#11]
##### SUMMARY
I'm unable to connect to Microsoft Exchange with a correct kerberos ticket using this command:
$session=New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://xxxxxx.xxxxx.domain -Authentication Negotiate -AllowRedirection

New-PSSession: [xxxxxx.xxxxx.domain] Connecting to remote server xxxxxx.xxxxx.domain failed with the following error message : MI_RESULT_ACCESS_DENIED For more information, see the about_Remote_Troubleshooting Help topic.

I can however connect to the same Exchange Server with this command:
Enter-PSSession xxxxxx.xxxxx.domain -Authentication Negotiate
[xxxxxx.xxxxx.domain]: PS C:\Users\quej\Documents>

##### LIBMI VERSION

```paste below
Major  Minor  Build  Revision
-----  -----  -----  --------
1      2      1      450
```

##### OS / ENVIRONMENT

Distribution: Fedora 32
pwsh version:7.0.3

Log output:
2020/09/30 14:21:34 [17242,17265] DEBUG: null(0): _ReadHeader - Full header has been received
2020/09/30 14:21:34 [17242,17265] WARNING: null(0): EventId=30170 Priority=WARNING cannot open http trace file: /opt/omi/var/log/omiclient-recv.trc, errno 13
2020/09/30 14:21:34 [17242,17265] WARNING: null(0): EventId=30170 Priority=WARNING cannot open http trace file: /opt/omi/var/log/omiclient-recv.trc, errno 13
2020/09/30 14:21:34 [17242,17265] DEBUG: null(0): _ReadHeader - check authorization
2020/09/30 14:21:34 [17242,17265] DEBUG: null(0): _ReadHeader - ACCESS DENIED reslt = 0
2020/09/30 14:21:34 [17242,17265] DEBUG: null(0): EventId=45128 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Post: 0x7f3c600f2cd0, msg(0x7f3c8803a5f8:4:PostResultMsg:0)
2020/09/30 14:21:34 [17242,17265] DEBUG: null(0): EventId=45129 Priority=DEBUG MI_Result = MI_RESULT_ACCESS_DENIED
2020/09/30 14:21:34 [17242,17265] DEBUG: null(0): EventId=45307 Priority=DEBUG MI_Client Operation Instance Result (async): session=0x7f3c600818d8, operation=0x7f3c600818f0, internal-operation=0x7f3c6008eaa0, resultCode=2, moreResults=FALSE

**Comment by jborean93** [comment]
Thanks for the bug report, can you share what version of Exchange you are connecting to? IIRC when Connection URI needs to have `/PowerShell` at the end as well so that would be worth a try.

**Comment by quej1976** [comment]
First, thanks for your work. I was searching for such a solution for a while. For the moment, i'm using cygwin's ssh+winpty to manage my Exchange servers from a linux terminal. 

The Exchange version is Exchange 2016 CU16

With the /Powershell I got a different error:
Client did not get proper response from server. For more information, see the about_Remote_Troubleshooting Help topic.

And here is the content of log file (it says access denied but i still can logon with Enter-PSSession):

[ClientAccessServer=xxxxxx,BackEndServer=,RequestId=11396f1c-c9bb-4a0a-bc4b-3a385daf9b34,TimeStamp=01/10/2020 18:55:35] Access Denied
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): _ReadHeader - Checking for full header...
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): _ReadHeader - Full header has been received
2020/10/01 18:55:35 [1561,1593] WARNING: null(0): EventId=30170 Priority=WARNING cannot open http trace file: /opt/omi/var/log/omiclient-recv.trc, errno 13
2020/10/01 18:55:35 [1561,1593] WARNING: null(0): EventId=30170 Priority=WARNING cannot open http trace file: /opt/omi/var/log/omiclient-recv.trc, errno 13
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): _ReadHeader - check authorization
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): _ReadHeader - is authorized. continue
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): _ReadHeader - OK exit
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): _ReadData - Begin. Head? 0
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): _ReadData - Received size: 139 / 139
2020/10/01 18:55:35 [1561,1593] WARNING: null(0): EventId=30170 Priority=WARNING cannot open http trace file: /opt/omi/var/log/omiclient-recv.trc, errno 13
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): _ReadData - call response callback
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45128 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Post: 0x7f1de816ec90, msg(0x7f1de8193918:4:PostResultMsg:0)
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45129 Priority=DEBUG MI_Result = MI_RESULT_FAILED
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45307 Priority=DEBUG MI_Client Operation Instance Result (async): session=0x7f1de81910d8, operation=0x7f1de81910f0, internal-operation=0x7f1de8191ab0, resultCode=1, moreResults=FALSE
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45292 Priority=DEBUG Session called: Session_ImpersonateClient
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45289 Priority=DEBUG Increase refcount for thunk handle: 0x7f1de8191c00
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45290 Priority=DEBUG Get correct thunk handle 0x7f1e41ccd800 from generic handle: 0x7f1de81910f0
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45295 Priority=DEBUG Enter Session_AccessCheck - session (0x7f1de8191ae0)
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45289 Priority=DEBUG Increase refcount for thunk handle: 0x7f1de818f630
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45290 Priority=DEBUG Get correct thunk handle 0x7f1e41ccd7c0 from generic handle: 0x7f1de8191ae0
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45288 Priority=DEBUG Decrease refcount without release thunk handle: 0x7f1de818f630
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45296 Priority=DEBUG Leave Session_AccessCheck on session (0x7f1de8191ae0) with for operation (close operation).
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45292 Priority=DEBUG Session called: Session_ImpersonateClient
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45289 Priority=DEBUG Increase refcount for thunk handle: 0x7f1de8191c00
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45290 Priority=DEBUG Get correct thunk handle 0x7f1e41ccd7b8 from generic handle: 0x7f1de81910f0
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45295 Priority=DEBUG Enter Session_AccessCheck - session (0x7f1de8191ae0)
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45289 Priority=DEBUG Increase refcount for thunk handle: 0x7f1de818f630
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45290 Priority=DEBUG Get correct thunk handle 0x7f1e41ccd770 from generic handle: 0x7f1de8191ae0
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45288 Priority=DEBUG Decrease refcount without release thunk handle: 0x7f1de818f630
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45296 Priority=DEBUG Leave Session_AccessCheck on session (0x7f1de8191ae0) with for operation (cancel operation).
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45314 Priority=DEBUG MI_Client Operation Cancel: operation=0x7f1de81910f0, internal-operation=0x7f1de8191ab0
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45292 Priority=DEBUG Session called: Session_ImpersonateClient
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45140 Priority=DEBUG InteractionProtocolHandler_Operation_Cancel 0x7f1de816ec90 -- ignoring because we have already posted the final result
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45292 Priority=DEBUG Session called: Session_RevertImpersonation
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45288 Priority=DEBUG Decrease refcount without release thunk handle: 0x7f1de8191c00
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45312 Priority=DEBUG MI_Client Operation Close: operation=0x7f1de81910f0, internal-operation=0x7f1de8191ab0
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45286 Priority=DEBUG Shutting down thunk handle: 0x7f1de8191c00
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45288 Priority=DEBUG Decrease refcount without release thunk handle: 0x7f1de8191c00
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45288 Priority=DEBUG Decrease refcount without release thunk handle: 0x7f1de8191c00
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45292 Priority=DEBUG Session called: Session_RevertImpersonation
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45292 Priority=DEBUG Session called: Session_RevertImpersonation
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45126 Priority=DEBUG InteractionProtocolHandler_Client_Ack_PostToInteraction 0x7f1de816ec90
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45287 Priority=DEBUG Release thunk handle: 0x7f1de8191c00
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45138 Priority=DEBUG InteractionProtocolHandler_Operation_Close 0x7f1de816ec90
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45311 Priority=DEBUG MI_Client Operation Close: Complete session=0x7f1de81910d8, operation=0x7f1de81910f0, internal-operation=0x7f1de8191ab0
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45292 Priority=DEBUG Session called: Session_UnregisterOperation
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45288 Priority=DEBUG Decrease refcount without release thunk handle: 0x7f1de8191c00
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45151 Priority=DEBUG ProtocolSocket: Ack on interaction [0x7f1de8183058]<-0x7f1dd0000dd8
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45134 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Ack 0x7f1de816ec90
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45152 Priority=DEBUG (E)ProtocolSocket: Close received (closed other: 0) on interaction [0x7f1de8183058]<-0x7f1dd0000dd8
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45147 Priority=DEBUG ProtocolSocket: triggering timeout on 0x7f1de8183018
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45136 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Close 0x7f1de816ec90
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45153 Priority=DEBUG (E)ProtocolSocket: 0x7f1de8183018 _ProtocolSocket_Finish
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45137 Priority=DEBUG InteractionProtocolHandler_Operation_Strand_Finish 0x7f1de816ec90
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45145 Priority=DEBUG SessionCloseCompletion_Release 0x7f1de808cf10 count is 1
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): _ReadData - response callback returned FALSE indicating it is done with the http request
2020/10/01 18:55:35 [1561,1593] ERROR: null(0): _RequestCallback - RequestCallbackRead failed
2020/10/01 18:55:35 [1561,1593] INFO: null(0): EventId=40033 Priority=INFO Selector_RemoveHandler: selector=0x7f1e41dd88a0, handler=0x7f1de81833f0, name=HTTP_CLIENT
2020/10/01 18:55:35 [1561,1593] DEBUG: null(0): EventId=45355 Priority=DEBUG Sock_Close: sock (106)
2020/10/01 18:55:35 [1561,2884] DEBUG: null(0): EventId=45298 Priority=DEBUG MI_Client Application Close: application=0x7f1de8249ee0, internal-application=0x7f1de8194120
2020/10/01 18:55:35 [1561,2884] DEBUG: null(0): EventId=45299 Priority=DEBUG MI_Client Application Close: Cancelling all operations on application=0x7f1de8249ee0, internal-application=0x7f1de8194120, session=0x7f1de818f550
2020/10/01 18:55:35 [1561,2884] DEBUG: null(0): EventId=45292 Priority=DEBUG Session called: Session_CancelAllOperations
2020/10/01 18:55:35 [1561,2884] DEBUG: null(0): EventId=45289 Priority=DEBUG Increase refcount for thunk handle: 0x7f1de818f630
2020/10/01 18:55:35 [1561,2884] DEBUG: null(0): EventId=45290 Priority=DEBUG Get correct thunk handle 0x7f1e1a7f7d88 from generic handle: 0x7f1e1a7f8ab0
2020/10/01 18:55:35 [1561,2884] DEBUG: null(0): EventId=45288 Priority=DEBUG Decrease refcount without release thunk handle: 0x7f1de818f630
2020/10/01 18:55:35 [1561,2884] DEBUG: null(0): EventId=45300 Priority=DEBUG MI_Client Application Close: Waiting for all sessions to shutdown on application=0x7f1de8249ee0, internal-application=0x7f1de8194120, number left=1

**Comment by jborean93** [comment]
So I think the last remaining thing you need to do is add `-Authentication Kerberos`. Exchange on prem does not actually support Negotiate auth and uses a pure Kerberos implementation. When testing this locally I get the same error as you do and checking the Wireshark packets I can see the auth response is a 400 (Bad Request). When I change it to `-Authentication Kerberos` it works just fine.

Apart from the crappy error messages there's not much I can do to change this. It's a limitation on the Exchange IIS auth handler where the auth token must be a pure Kerberos token and not one wrapped in a Negotiate token.

**Comment by quej1976** [comment]
That's awesome, it works!
