### ISSUE TITLE
Any way to leverage this from PowerShell SDK?

### ISSUE THREAD

**Issue by jeff-simeon** [jborean93/omi#36]
##### SUMMARY
PowerShell Core has abandoned support of OMI and PowerShell SDK can't be used for Exchange Online even with the symbolic link created to OpenSSL.

The issue is documented here 
https://github.com/PowerShell/PowerShell/issues/10600

with a minimally reproducible example here:
https://github.com/JeffN825/PowerShellWSManBug

Is it possible to make this work using your fork?

Thanks! Great work on this project.

##### OS / ENVIRONMENT
Mac OS Big Sur

**Comment by jborean93** [comment]
It should be possible, you essentially need to ensure the `libmi` and `libpsrpclient` in the pwsh dir are replaced. The `Install-WSMan` cmdlet distributed in `PSWSMan` does this for you but there's nothing stopping you from doing it yourself. You could also add an `ImportResolver` as mentioned in https://github.com/jborean93/omi/issues/24#issuecomment-798995921 to ensure `libpsrpclient` loads the so/dylib distributed by PSWSMan.

**Comment by jeff-simeon** [comment]
Thanks. I tried this and didn't make it too far.

I added this to my csproj:
```
  <ItemGroup>
    <Content Include="PSWSMan/2.2.1/lib/macOS-3/*.*" CopyToOutputDirectory="Always" Link="%(Filename)%(Extension)" />
  </ItemGroup>
```
which gets the dylib's copied to my bin directory

Added this to my entry point
```
System.Runtime.InteropServices.NativeLibrary.SetDllImportResolver(typeof(PSObject).Assembly, ImportResolver);
```
and validated my resolver gets called:
```
public static IntPtr ImportResolver(string libraryName, Assembly assembly, DllImportSearchPath? searchPath)
        {   
            if (libraryName == "libpsrpclient" || libraryName == "libmi") {
                libraryName = Path.Combine(Path.GetDirectoryName(typeof(Program).Assembly.Location), $"{libraryName}.dylib");
            }      

            return NativeLibrary.Load(libraryName, assembly, searchPath);
        }
```

Unfortunately, this blows up at 
```
            return NativeLibrary.Load(libraryName, assembly, searchPath);
```
with the exception
```
An exception of type 'System.DllNotFoundException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Unable to load shared library '/Users/jeff/dev/PowerShellWSManBug/bin/Debug/net5.0/libpsrpclient.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(/Users/jeff/dev/PowerShellWSManBug/bin/Debug/net5.0/libpsrpclient.dylib, 1): Library not loaded: @loader_path/libssl.3.dylib
  Referenced from: /Users/jeff/dev/PowerShellWSManBug/bin/Debug/net5.0/libmi.dylib
  Reason: image not found'
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
```
the file is, of course, there

**Comment by jborean93** [comment]
The number in the distribution refers to the OpenSSL version it is linked against. Because each OpenSSL major version is not ABI (and sometimes API) compatible the version you use must reflect what OpenSSL version you have available. You most likely have OpenSSL 1.1.x installed with brew (3 is still in the release candidate phase) so you should include `macOS-1.1`.

MacOS also makes things a bit more difficult as it's trying to find `libssl` and `libcrypto` relative to `libmi.dylib`. The `Install-WSMan` cmdlet will create the 2 symlinks for these files in the same dir as `libmi.dylib` to point to the actual `libssl` and `libcrypto` either provided by `brew` or `port`. You will either:

* Have to also create the symlinks and copy it in place as well, or
* Use `install_name_tool` to adjust the `libssl` and `libcrypto` entries in `libmi.dylib` to the location on your host

```bash
# Must be done for libssl and libcrypto. The target path is dependent on your host in question
# For brew see 'echo "$( brew --prefix openssl )/lib"'
# For port see 'port contents openssl'

install_name_tool -change \
    libmi.dylib \
    @loader_path/libssl.1.1.dylib \
    /usr/local/opt/openssl@1.1/lib/libssl.dylib
```

It's a mess unfortunately but unfortunately I don't know of a nice way to achieve all this that is universal across macOS distributions. The proper solution is to adjust the code so it uses Apple's native TLS library  but that's a lot more than I can chew at the moment.

> if (libraryName == "libpsrpclient" || libraryName == "libmi") {

As an FYI you only need to adjust `libpsrpclient` for the .NET resolver. PowerShell imports `libpsrpclient` which in turn imports `libmi` through the dylib loading process completely outside of .NET.

**Comment by jeff-simeon** [comment]
Thanks!

I must have done something wrong...I install openssl via MacPorts (it's not available on Brew anymore that I can see). 

I grabbed the path of my install
```
Jeffs-MBP ~ % port contents openssl | grep dylib  
  /opt/local/lib/engines-1.1/capi.dylib
  /opt/local/lib/engines-1.1/padlock.dylib
  /opt/local/lib/libcrypto.1.1.dylib
  /opt/local/lib/libcrypto.dylib
  /opt/local/lib/libssl.1.1.dylib
  /opt/local/lib/libssl.dylib
```

I switched to 1.1
```
  <ItemGroup>
    <Content Include="PSWSMan/2.2.1/lib/macOS-1.1/*.*" CopyToOutputDirectory="Always" Link="%(Filename)%(Extension)" />
  </ItemGroup>
```

and I ran this command from my bin/Debug/net5.0 directory
```
net5.0 % sudo install_name_tool -change \
    libmi.dylib \
    @loader_path/libssl.1.1.dylib \
    /opt/local/lib/libssl.1.1.dylib
```
But I still get the error
```
An exception of type 'System.DllNotFoundException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Unable to load shared library '/Users/jeff/dev/PowerShellWSManBug/bin/Debug/net5.0/libpsrpclient.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(/Users/jeff/dev/PowerShellWSManBug/bin/Debug/net5.0/libpsrpclient.dylib, 1): Library not loaded: @loader_path/libssl.1.1.dylib
```

**Comment by jborean93** [comment]
Hmm based on the error it is still trying to find `libssl` using `@loader_path/libssl.1.1.dylib` which shouldn't be the case after running `install_name_tool`. Can you run `otool -L libpsrpclient.dylib` and `otool -L libmi.dylib` and share those results. You should have to run `install_name_tool` as root as well. It just edits the ELF headers of the dylib specified so as long as you have rights to the file you are good to go.

**Comment by jborean93** [comment]
Ah sorry I gave you the wrong order of arguments it should be

```bash
install_name_tool -change \
    @loader_path/libssl.1.1.dylib \
    /opt/local/lib/libssl.1.1.dylib \
    libmi.dylib
```

The first argument is what to change, the 2nd is what to change it to, and the 3rd is the library to change.

**Comment by jeff-simeon** [comment]
Progress!

```
An unhandled exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: [outlook.office365.com] Connecting to remote server outlook.office365.com failed with the following error message : error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed For more information, see the about_Remote_Troubleshooting Help topic.
```

Any idea why certificate validation would be failing? Needless to say, I checked in a regular PowerShell command prompt and didn't get a failure.

**Comment by jeff-simeon** [comment]
Got it working! Thank you!
Just FYI - as an experiment - I tried using the same `install_name_tool` commands on `bin/runtimes/osx/native/libmi.dylib' and it didn't work (still broke with the original `image not found` error)...so clearly it's not just an OpenSSL path issue.

**Comment by jeff-simeon** [comment]
I'm down to one final issue it seems. This isn't a problem with anything related to your OMI fork, but if you have any knowledge on this, would certainly appreciate the help. Exchange Online works fine, but the following code for Security Center works perfectly from Windows (both powershell and pwsh), but bombs on Mac with the error (exact same code with the exact same token...just copy/pasted from Windows to Mac): 
`Connecting to remote server ps.compliance.protection.outlook.com failed with the following error message : Basic Authorization failed for user`. 

On Mac, this fails both using the default libmi as well as the one from PSWSMan.

```

$global:InformationPreference = 'Continue'
$global:ErrorActionPreference = 'Stop'
$global:ProgressPreference = 'SilentlyContinue'

function Get-Session {
    Get-PSSession |? ConfigurationName -eq 'Microsoft.Exchange'
}

function Remove-Session {
    foreach($s in Get-Session) { 
        try { 
            Write-Information "Removing existing open PSSession $($s.Id) for Microsoft.Exchange at https://ps.compliance.protection.outlook.com/powershell-liveid/?BasicAuthToOAuthConversion=true."        
            $s | Remove-PSSession
        } 
        catch {
            Write-Warning "Encountered an error removing PSSession $($s.Id) ($($_.Exception.Message))."      
        }
    }
}

function Initialize-Session {
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    $userCredential = New-Object System.Management.Automation.PSCredential('***', (ConvertTo-SecureString 'Bearer ***' -AsPlainText -Force))
    $option = New-PSSessionOption
    $option.IdleTimeout = [TimeSpan]::FromSeconds(60) # inline setting of this property via New-PSSessionOption is not supported on non-Windows platforms
    $option.OpenTimeout = [TimeSpan]::FromSeconds(60)
    Write-Information 'Creating PSSession for Microsoft.Exchange at https://ps.compliance.protection.outlook.com/powershell-liveid/?BasicAuthToOAuthConversion=true.'
    $connectionUri = 'https://ps.compliance.protection.outlook.com/powershell-liveid?BasicAuthToOAuthConversion=true'
    if ($IsMacOS) {
        # https://github.com/PowerShell/PowerShell/issues/7276
        $connectionUri = $connectionUri.Replace('&', '&amp;')
    }
    Write-Host $connectionUri
    $session = New-PSSession -SessionOption $option -ConfigurationName Microsoft.Exchange -ConnectionUri $connectionUri -Credential $userCredential -Authentication Basic -AllowRedirection -WarningAction SilentlyContinue
    $module = Import-PSSession $session -DisableNameChecking -AllowClobber -WarningAction SilentlyContinue
    Import-Module $module -Global -WarningAction SilentlyContinue
    Write-Information "Imported PSSession $($session.Id) and Module for Microsoft.Exchange at https://ps.compliance.protection.outlook.com/powershell-liveid/?BasicAuthToOAuthConversion=true in $($sw.ElapsedMilliseconds)ms."
}

Remove-Session
Initialize-Session 
```

**Comment by jeff-simeon** [comment]
Small update - I tried using Fiddler Anywhere to compare the activity on Windows vs Mac and unfortunately, it doesn't look like PowerShell Core on Mac supports the notion of proxies for WinRM, so I can't get Fiddler to intercept the traffic on Mac...so I'm kind of stuck poking in the dark.

**Comment by jborean93** [comment]
I'm unsure really, modern/basic auth is really quite simple from OMI's perspective. It's adding the base64 encoded value you specify so there's really no platform specific logic at play here. I would just make sure the method you use to retrieve the bearer token is the same across the platform and the value it is has a similar structure. I would also remove the `$connectionUri = $connectionUri.Replace('&', '&amp;')` and see if it's actually required anymore.

As for proxying you might have some luck setting the env var `https_proxy=http://my-fidler-host` as you start your app as it might just use that by default.

**Comment by jeff-simeon** [comment]
```
$connectionUri = $connectionUri.Replace('&', '&amp;')
```
yes - tried this as well - it definitely IS required for Exchange Online because EXO required the extra query string parameter DelegatedOrg which SC does not...so with the SC config it is a no-op because there is no & in the query string

```
https_proxy=http://my-fidler-host
```
yep - already tried that to no avail :(

what's so strange is that it's literally the exact same code and tokens that work/don't work between Windows/Mac

My hunch is that there is something about the content of the XML in the POST requests that is making it lose the fact that it's an OAuth attempt vs a regular basic auth attempt.

**Comment by jborean93** [comment]
Not sure what else that could be done, you can enable DEBUG logging for OMI and look at the raw messages there. It should also contain the headers that are sent https://github.com/jborean93/omi#troubleshooting. I know I was definitely able to connect to EXO without replacing the values in the connection URI but I was using the Office 365 URL specified in https://gist.github.com/jborean93/d50041c2a0fed20e87aa46ba32381754#file-new-exopssession-ps1-L176-L188. Unfortunately at this point you are at the mercy of what OMI provides you and are beyond my knowledge sorry.

**Comment by jeff-simeon** [comment]
Thanks - I enabled the logs and that got me on the right track. It's the redirection...

`AllowRedirection` in `New-PSSession` seems to be broken for Mac.

If I use the connection URI 
`$connectionUri = 'https://nam10b.ps.compliance.protection.outlook.com/powershell-liveid/?BasicAuthToOAuthConversion=true'`

it works (note the extra nam10b part of the hostname)

I'll see if I can get the redirected hostname manually using a REST call, unless you have an idea on the matter.
