### ISSUE TITLE
can the Mac dylib be packaged and distributed with brew?

### ISSUE THREAD

**Issue by TheBigBear** [jborean93/omi#5]
##### SUMMARY

What are the exact manual steps required to get latest powershell-core to work using the re-compiled dylib from this project? What effort would be involved in packing this up for brew distribution? 

##### LIBMI VERSION

```paste below

```

##### OS / ENVIRONMENT

Mac OS Catalina fully patched

**Comment by jborean93** [comment]
Closing as I believe that answers your question.
