### ISSUE TITLE
Please implement as custom remote connection plugin

### ISSUE THREAD

**Issue by SteveL-MSFT** [jborean93/omi#51]
##### SUMMARY
https://github.com/PowerShell/PowerShell-RFC/blob/master/Archive/Draft/RFC0063-Custom-Remote-Connections.md

Example plugin

https://github.com/PaulHigin/NamedPipeConnection

**Comment by jborean93** [comment]
So the trouble with this is WSMan doesn't follow the OutOfProc style connection plugins that the custom model follows. Trying to do so would be quite complex and would require some middle man to try and map the WSMan actions with the OutOfProc model.

The other problem I see is that the custom connection model requires you to use a dedicated cmdlet to build the PSSession and pass that to `Invoke-Command`. This is a poor UX for people used to just doing `Invoke-Command computername {}` or just `Enter-PSSession computername`. It also means modules like EXO or anything else that creates a PSSession won't work properly as they are building the connection from the existing `WSManConnectionInfo` that this is somewhat hijacking.

Finally I feel like the stuff in `omi` is complete. The code isn't that stable and not really great to work with so I'm reluctant to try and add more features aside for bugfixes. I'm hoping to eventually implement a pure C# implementation of the WSMan code simplifying and stabilising all this but I don't know what that would look like right now.
