### ISSUE TITLE
Get-OmiVersion.ps1 does not exist

### ISSUE THREAD

**Issue by Yannik** [jborean93/omi#53]
Hi @jborean93,

in the issue template of this repo, it is requested that users run [https://github.com/jborean93/omi/.github/tools/Get-OmiVersion.ps1](https://github.com/jborean93/omi/.github/tools/Get-OmiVersion.ps1) and copy the output into the issue.

However, this file does not exist.

**Comment by jborean93** [comment]
Thanks, I'll update the template to no longer reference this function.

**Comment by jborean93** [comment]
Fixed with https://github.com/jborean93/omi/commit/3b1545fd0d576c296d5ff15b679392b55a283197
