### ISSUE TITLE
work with module PSWSMan in code without  install powershell?

### ISSUE THREAD

**Issue by B-CCCPcekca-HET** [jborean93/omi#75]
##### SUMMARY

I call ps1 scripts  using Csharp and powershell sdk on Debian 12.
But I can't import and install the PSWSMan module in code. Powershell is not installed on the system. Is it possible to work with the module without installing powershell on the system?

##### MODULE VERSION

```paste below
2.3.1
```

##### OS / ENVIRONMENT

Debian 12

**Comment by jborean93** [comment]
You can manually copy the `libmi` and `libpsrpclient` libs in a way that it is picked up by PowerShell automatically or set up a native library resolver to point to the correct ones. https://github.com/jborean93/omi/issues/57#issuecomment-1312854359 goes into a bit more detail on how to do something like that.

**Comment by B-CCCPcekca-HET** [comment]
> Вы можете вручную скопировать библиотеки `libmi`и `libpsrpclient`таким образом, чтобы PowerShell автоматически их подхватил, или настроить собственный определитель библиотек, чтобы он указывал на правильные библиотеки. [#57 (комментарий)](https://github.com/jborean93/omi/issues/57#issuecomment-1312854359) более подробно описывает, как сделать что-то подобное.

thanks, this helped me
